php:
   build: .
   working_dir: /home/
   volumes:
 
     - ./php.ini:/usr/local/etc/php/php.ini
   environment:
    - DOCKERHOST=192.168.0.49

   extra_hosts:
     - "lara.local:192.168.0.49"
     - dockerhost:192.168.0.49
   hostname: lara.local
   domainname: local 
   ports:
     - 80:80  